import type { Config } from "tailwindcss";

// Tokens del sistema de diseño "Emerald Finance", extraídos de los mockups
// de referencia (notificaciones, scanner, estrategia de deuda). Mantener
// estos nombres tal cual: todos los componentes en /components los usan
// directamente (bg-primary, text-on-surface-variant, font-currency-display, etc.).
const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#d0dbed",
        "on-error-container": "#93000a",
        secondary: "#ae2f34",
        "primary-fixed": "#6ffbbe",
        "primary-container": "#10b981",
        "secondary-fixed": "#ffdad8",
        "on-primary": "#ffffff",
        outline: "#6c7a71",
        "on-tertiary-container": "#523200",
        "secondary-fixed-dim": "#ffb3b0",
        "secondary-container": "#ff6b6b",
        "on-primary-container": "#00422b",
        "on-secondary-fixed": "#410006",
        "on-secondary-container": "#6d0010",
        "on-primary-fixed-variant": "#005236",
        "outline-variant": "#bbcabf",
        error: "#ba1a1a",
        background: "#f8f9ff",
        "surface-container": "#e6eeff",
        "on-secondary": "#ffffff",
        "surface-bright": "#f8f9ff",
        "primary-fixed-dim": "#4edea3",
        "surface-tint": "#006c49",
        "inverse-primary": "#4edea3",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#8c1520",
        "tertiary-fixed": "#ffddb8",
        "on-surface": "#121c2a",
        "error-container": "#ffdad6",
        "inverse-surface": "#27313f",
        "surface-container-highest": "#d9e3f6",
        "surface-container-low": "#eff4ff",
        "on-primary-fixed": "#002113",
        surface: "#f8f9ff",
        "on-error": "#ffffff",
        "on-surface-variant": "#3c4a42",
        "on-background": "#121c2a",
        "surface-container-high": "#dee9fc",
        tertiary: "#855300",
        "on-tertiary": "#ffffff",
        primary: "#006c49",
        "surface-variant": "#d9e3f6",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary-fixed-variant": "#653e00",
        "tertiary-fixed-dim": "#ffb95f",
        "tertiary-container": "#e29100",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      spacing: {
        lg: "40px",
        base: "8px",
        gutter: "24px",
        md: "24px",
        "container-max": "1200px",
        "margin-mobile": "16px",
        sm: "12px",
        xs: "4px",
        xl: "64px",
      },
      fontFamily: {
        "headline-lg": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "label-md": ["JetBrains Mono"],
        "display-lg": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "currency-display": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "currency-display": ["36px", { lineHeight: "44px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
      boxShadow: {
        ambient: "0 4px 15px rgba(0, 0, 0, 0.04)",
        "ambient-hover": "0 8px 25px rgba(0, 0, 0, 0.08)",
        modal: "0 10px 30px rgba(0, 0, 0, 0.1)",
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};

export default config;
